version: "3.8"

services:
  auth-server:
    image: auth-server:0.0.1-SNAPSHOT
    container_name: auth-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net
    restart: unless-stopped

  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-server
      - joke-service
      - quotee-service
    networks:
      - microservices-net
    restart: unless-stopped

  joke-service:
    image: joke-service:0.0.1-SNAPSHOT
    container_name: joke-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-server
    networks:
      - microservices-net
    restart: unless-stopped

  quotee-service:
    image: quotee-service:0.0.1-SNAPSHOT
    container_name: quotee-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-server
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge