services:
  auth-server:
    build: ./auth-server
    ports:
      - "8081:8081"
    # image: auth-server   <-- Ta bort eller kommentera denna rad

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
      - joke-service
      - quote-service
    # image: api-gateway

  joke-service:
    build: ./joke-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-server
    # image: joke-service

  quote-service:
    build: ./quote-service
    ports:
      - "8083:8083"
    depends_on:
      - auth-server
    # image: quote-service
