server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-server:8080
          predicates:
            - Path=/api/auth/**
        - id: joke-service
          uri: http://joke-service:8082
          filters:
            - StripPrefix=1
          predicates:
            - Path=/api/jokes/**
        - id: quote-service
          uri: http://quotee-service:8083
          predicates:
            - Path=/api/quotes/**
          filters:
              - StripPrefix=1

  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
