server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: joke-service
          uri: http://localhost:8082
          predicates:
            - Path=/joke/**
        - id: quote-service
          uri: http://localhost:8083
          predicates:
            - Path=/quote/**
