server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-server:8081
          predicates:
            - Path=/api/auth/**
        - id: joke-service
          uri: http://joke-service:8082
          predicates:
            - Path=/api/jokes/**
        - id: quote-service
          uri: http://quote-service:8083
          predicates:
            - Path=/api/quotes/**

  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
